spring:
  jpa:
    database: postgresql
    hibernate:
      dialect: org.hibernate.dilect.PostgreSQLDialect
      ddl-auto: update
      properties.hibernate.format-sql: true
      show-sql: true

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://ec2-3-217-251-77.compute-1.amazonaws.com/dddjn7vrp92fnl
    username: pqfstlpghdggdw
    password: ad531c5f532add1712a2f04e3dcd4662e447e74de80d82cc6d048e37f212bfe7
    platform: postgres
    driver-class-name: org.postgresql.Driver

jwt:
  secret:
    key: fast_campus.sns-application-2023.secret_key
  token:
    expired-time-ms: 2592000000
