spring:
  jpa:
    database: postgresql
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://ec2-44-205-41-76.compute-1.amazonaws.com/dakents1ian48g
    username: eafobkwjtbiagj
    password: 88572b30bdf582c6f5f860b3b68a591a53b494159bbbc3baace20ebc297bb6ee
    platform: postgres
    driver-class-name: org.postgresql.Driver

  redis:
    url:  redis://:p9f0a55813d037f316d8346e66e443e8846158102c0fac3c86c9646870022e355@ec2-44-207-143-113.compute-1.amazonaws.com:32159

jwt:
  secret:
    key: fast_campus.sns-application-2023.secret_key
  token:
    expired-time-ms: 2592000000
